import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
        <header className="fixed top-0 z-50 w-full bg-[#f7f9fb]/80 backdrop-blur-md shadow-[0_10px_40px_rgba(24,32,52,0.06)]">
        <nav className="flex justify-between items-center w-full px-8 py-6 max-w-7xl mx-auto font-medium tracking-tight">
          <div className="text-xl font-bold tracking-tighter text-[#182034]">Areeb Uzzaman</div>
          <div className="hidden md:flex gap-8 items-center">
            <Link className="text-[#182034] border-b-2 border-[#182034] pb-1 transition-all duration-300" href="/">Home</Link>
            <Link className="text-[#74777f] hover:text-[#182034] transition-colors" href="/policy_research">Projects</Link>
            <Link className="text-[#74777f] hover:text-[#182034] transition-colors" href="/insights">Insights</Link>
            <Link className="text-[#74777f] hover:text-[#182034] transition-colors" href="/experience">Experience</Link>
            <Link className="ml-4 px-6 py-2 bg-[#182034] text-[#ffffff] rounded-lg text-sm font-bold hover:opacity-80 transition-all active:scale-95 duration-200" href="/archieve_login">Archive Login</Link>
          </div>
          {/* Mobile Menu Icon */}
          <div className="md:hidden">
            <span className="material-symbols-outlined text-[#182034]">menu</span>
          </div>
        </nav>
      </header>

        </div>
        {children}
          {/* Footer */}
      <footer className="bg-[#f2f4f6] w-full ">
        <div className="flex flex-col md:flex-row justify-between items-center px-24 py-12 w-full max-w-7xl mx-auto text-sm leading-relaxed text-[#182034]">
          <div className="mb-6 md:mb-0">
            © 2024 Areeb Uzzaman. All rights reserved.
          </div>
          <div className="flex gap-8">
            <Link className="text-[#74777f] hover:text-[#182034] underline transition-all ease-in-out duration-300" href="#">LinkedIn</Link>
            <Link className="text-[#74777f] hover:text-[#182034] underline transition-all ease-in-out duration-300" href="#">GitHub</Link>
            <Link className="text-[#74777f] hover:text-[#182034] underline transition-all ease-in-out duration-300" href="#">Email</Link>
          </div>
        </div>
      </footer>
        </body>
    </html>
  );
}
